title: Graphite theme
author: GitHub User
email: your-email@domain.com

social_media_links:
  - link: https://twitter.com/jekyllrb/
    icon: fa-twitter
  - link: https://curtisupdike.github.io/graphite/
    icon: fa-github

theme_colors: # enclose hex codes in ' '
  theme: '#be5141'
  text: '#58595e'
  background: '#fff'
  code-block: '#fbf8f4'

show_rss: true # set to false to exclude rss icon from footer

plugins:
 - jekyll-feed
 - jekyll-seo-tag
